# Generated by Django 4.2.11 on 2024-10-08 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aisearchbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('call', 'call'), ('text_message', 'text messages'), ('voice_email', 'voice email'), ('email', 'email'), ('note', 'note'), ('convert', 'convert')], max_length=100)),
                ('comment', models.TextField()),
                ('action_datetime', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_actions', to='aisearchbot.candidateprofiles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
