# Generated by Django 4.2.11 on 2024-10-10 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileactions',
            name='action_type',
            field=models.CharField(choices=[('call', 'call'), ('message', 'text messages'), ('voice_email', 'voice email'), ('email', 'email'), ('note', 'note'), ('convert', 'convert')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profileactions',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
