# Generated by Django 4.2.11 on 2024-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_profileactions_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileactions',
            name='action_type',
            field=models.CharField(choices=[('call', 'call'), ('text_message', 'text messages'), ('voice_email', 'voice email'), ('email', 'email'), ('note', 'note'), ('convert', 'convert'), ('opened_profile', 'Opened Profile')], max_length=100),
        ),
    ]
