# Generated by Django 4.2.11 on 2024-05-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company'), ('admin', 'Admin'), ('auth_user', 'Auth_User'), ('super_admin', 'Super_Admin')], default='user', max_length=20),
        ),
    ]
