# Generated by Django 4.2.11 on 2024-05-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscription_user_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('company', 'Company'), ('contact', 'Contact'), ('admin', 'Admin'), ('auth_user', 'Auth_User'), ('super_admin', 'Super_Admin')], default='user', max_length=20),
        ),
    ]
