# Generated by Django 4.2.11 on 2024-05-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_contact_company_name_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
