# Generated by Django 4.2.11 on 2024-06-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_company_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
