# Generated by Django 4.2.11 on 2024-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
