# Generated by Django 4.2.11 on 2024-06-11 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_subscriptionplans_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.PositiveIntegerField(blank=True, null=True)),
                ('saved_searches_limit', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('users_limit', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('credits', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
