# Generated by Django 4.2.11 on 2024-06-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customplan_remaining_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customplan',
            name='searches_per_month',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
    ]
