# Generated by Django 4.2.11 on 2024-06-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_subscription_is_trial_user_has_used_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_interval',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('biweekly', 'Biweekly')], default='monthly', max_length=20),
        ),
    ]
