# Generated by Django 4.2.11 on 2024-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_subscription_subscription_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
