# Generated by Django 4.2.11 on 2024-06-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_subscription_user_payment_method_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarysubscriptiondata',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
