# Generated by Django 4.2.11 on 2024-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_usersession_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customplan',
            name='simultaneous_connections_limit',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplans',
            name='simultaneous_connections_limit',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
