version: '3.2'

services:
  flunter-frontend:
    container_name: "${PROJECT_NAME}_frontend_${ENV}"
    build:
      context: ./
      dockerfile: Dockerfile
    # command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5677 manage.py runserver 0.0.0.0:8000 --nothreading"]
    volumes:
      - "./:/code"
    ports:
      - $WEB_PORT:8000
      - 5677:5677
    depends_on:
      - flunter-db

  flunter-db:
    container_name: "${PROJECT_NAME}_postgres_${ENV}"
    image: postgis/postgis:14-3.3
    volumes:
      - flunter-postgres-data:/var/lib/postgres
    environment:
      POSTGRES_DB: "${FLUNTER_DB_NAME}"
      POSTGRES_USER: "${FLUNTER_DB_USER}"
      POSTGRES_PASSWORD: "${FLUNTER_DB_PASSWORD}"

volumes:
  flunter-postgres-data: