# Generated by Django 4.2.11 on 2024-10-04 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aisearchbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email1', models.BooleanField(default=False)),
                ('is_email2', models.BooleanField(default=False)),
                ('is_phone1', models.BooleanField(default=False)),
                ('is_phone2', models.BooleanField(default=False)),
                ('is_favourite', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aisearchbot.candidateprofiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
