# Generated by Django 4.2.11 on 2024-10-04 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
