# Generated by Django 4.2.11 on 2024-10-07 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisearchbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asb', '0002_alter_useraccesslog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccesslog',
            name='is_favourite',
        ),
        migrations.CreateModel(
            name='FavoriteCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aisearchbot.candidateprofiles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_candidates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
