# Generated by Django 4.2.11 on 2024-11-15 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aisearchbot', '0001_initial'),
        ('asb', '0003_remove_useraccesslog_is_favourite_favoritecandidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesslog',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='aisearchbot.candidateprofiles'),
        ),
    ]
