# Generated by Django 4.2.11 on 2024-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_searches_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='companies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='head_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='job_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searches',
            name='search_via_op',
            field=models.CharField(choices=[('or', 'or'), ('and', 'and')], default='or', max_length=25),
        ),
        migrations.AddField(
            model_name='searches',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
