# Generated by Django 4.2.11 on 2024-09-25 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0004_searches_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedusers',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
