# Generated by Django 4.2.11 on 2024-11-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_searches_companies_searches_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='seniority_levels',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
