# Generated by Django 4.2.11 on 2024-11-11 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_sharedusers_belongs_to'),
        ('web', '0006_searches_seniority_levels'),
    ]

    operations = [
    ]
