# Generated by Django 4.2.11 on 2024-11-14 05:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_alter_needs_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='needs',
            name='head_count',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
