# Generated by Django 4.2.11 on 2024-11-05 07:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_searches', '0002_alter_searches_search_via_alter_searches_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='search_via',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
