# Generated by Django 4.2.11 on 2024-11-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved_searches', '0002_alter_searches_user'),
        ('saved_searches', '0003_alter_searches_search_via'),
    ]

    operations = [
    ]
