# Generated by Django 4.2.11 on 2024-11-06 10:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_searches', '0004_merge_20241105_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='search_via',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email1', 'Email 1'), ('email2', 'Email 2'), ('phone1', 'Phone 1'), ('phone2', 'Phone 2')], max_length=100), blank=True, null=True, size=None),
        ),
    ]
