# Generated by Django 4.2.11 on 2024-11-13 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_searches', '0005_alter_searches_search_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='searches',
            name='seniority',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, null=True, size=None),
        ),
    ]
